version: 2
updates:
  - package-ecosystem: pip
    directory: /Harsimrat_Singh
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
